name: front-linter

on:
  push:
    branches: ['main', 'development']
  pull_request:
    branches: ['main', 'development']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint scan
        id: eslint-scan
        run: npm run lint || exit 0

      - name: Run ESLint fix if needed
        if: steps.eslint-scan.outcome == 'failure'
        run: npm run lint:fix

      - name: Run Prettier
        run: npm run format

      - name: Run next build
        run: npm run build
